width: 800
height: 480
background_color: "white"
background_color_weather: "white"
text_color: "black"
image_format: "bmp"
max_font_size: 51
min_font_size: 10
font_path: "/Library/Fonts/Arial\ Unicode.ttf"
output_path: "eink_display.bmp"

station: KOHX # KJAX #KOHX #CONUS-LARGE #KOHX # KOHX # KTYX SOUTHROCKIES  KTBW   KHTX KHPX
output_mode: color # Options: "color", "grayscale", "binary"

radar_mode: fit # "crop"  # or "fit"


colors:
    red: (255, 0, 0)   # red
    green: (0, 255, 0) # green
    blue: (0, 0, 255)   # blue
    yellow: (255, 255, 0) # yellow
    orange: (255, 128, 0)  # orange
    white: (255, 255,255)
    black: (0, 0, 0)
    grey: (128, 128, 128)

stations: 
    - KABR
    - KABX
    - KAKQ
    - KAMA
    - KAMX
    - KAPX
    - KARX
    - KATX
    - KBBX
    - KBGM
    - KBHX
    - KBIS
    - KBLX
    - KBMX
    - KBOX
    - KBRO
    - KBUF
    - KBYX
    - KCAE
    - KCBW
    - KCBX
    - KCCX
    - KCLE
    - KCLX
    - KCRP
    - KCXX
    - KCYS
    - KDAX
    - KDDC
    - KDFX
    - KDGX
    - KDIX
    - KDLH
    - KDMX
    - KDOX
    - KDTX
    - KDVN
    - KDYX
    - KEAX
    - KEMX
    - KENX
    - KEOX
    - KEPZ
    - KESX
    - KEVX
    - KEWX
    - KEYX
    - KFCX
    - KFDR
    - KFDX
    - KFFC
    - KFSD
    - KFSX
    - KFTG
    - KFWS
    - KGGW
    - KGJX
    - KGLD
    - KGRB
    - KGRK
    - KGRR
    - KGSP
    - KGWX
    - KGYX
    - KHDC
    - KHDX
    - KHGX
    - KHNX
    - KHPX
    - KHTX
    - KICT
    - KICX
    - KILN
    - KILX
    - KIND
    - KINX
    - KIWA
    - KIWX
    - KJAX
    - KJGX
    - KJKL
    - KLBB
    - KLCH
    - KLGX
    - KLNX
    - KLOT
    - KLRX
    - KLSX
    - KLTX
    - KLVX
    - KLWX
    - KLZK
    - KMAF
    - KMAX
    - KMBX
    - KMHX
    - KMKX
    - KMLB
    - KMOB
    - KMPX
    - KMQT
    - KMRX
    - KMSX
    - KMTX
    - KMUX
    - KMVX
    - KMXX
    - KNKX
    - KNQA
    - KOAX
    - KOHX
    - KOKX
    - KOTX
    - KPAH
    - KPBZ
    - KPDT
    - KPOE
    - KPUX
    - KRAX
    - KRGX
    - KRIW
    - KRLX
    - KRTX
    - KSFX
    - KSGF
    - KSHV
    - KSJT
    - KSOX
    - KSRX
    - KTBW
    - KTFX
    - KTLH
    - KTLX
    - KTWX
    - KTYX
    - KUDX
    - KUEX
    - KVAX
    - KVBX
    - KVNX
    - KVTX
    - KVWX
    - KYUX
    - PABC
    - PACG
    - PAEC
    - PAHG
    - PAIH
    - PAKC
    - PAPD
    - PGUA
    - PHKI
    - PHKM
    - PHMO
    - PHWA
    - TJUA

