width: 800
height: 480
background_color: "white"
background_color_weather: "white"
text_color: "black"
image_format: "bmp"
max_font_size: 51
min_font_size: 10
font_path: "/Library/Fonts/Arial\ Unicode.ttf"
output_path: "eink_display.bmp"

station: CONUS-LARGE #KOHX # KOHX # KTYX SOUTHROCKIES  KTBW   KHTX KHPX
output_mode: color # Options: "color", "grayscale", "binary"

radar_mode: fit # "crop"  # or "fit"